language: node_js
node_js:
  - "stable"
install:
  - npm ci
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE pplite;' -U postgres
script:
  - npm run test
after_success:
  - npm run coverage
env:
  global:
    -CODECLIMATE_REPO_TOKEN=28adb2e5a02dd2e19fbbba9b9ea8101542bec4dbc9a58c654f471087c548bee1